<div class="container-lg">
    <h1 class="display-4 my-4">Сайты</h1>
    
    <table class="table table-bordered table-hover" data-test="urls">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Имя</th>
                <th>Последняя проверка</th>
                <th>Код ответа</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($urls as $url): ?>
            <tr>
                <td><?= htmlspecialchars($url['id']) ?></td>
                <td><a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                <td><?= $url['last_check']['created_at'] ?? '' ?></td>
                <td><?= $url['last_check']['status_code'] ?? '' ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>