<?php require 'components/header.phtml'; ?>

<main  class="container-lg flex-grow-1">
    <div class="row justify-content-center">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
                <h1 class="display-3">Анализатор страниц</h1>
                <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
            
            <form action="/urls" method="post" class="mb-5">
                <div class="input-group mb-3">
                    <input type="text" name="url[name]" value="" class="form-control form-control-lg <?= (isset($errors)) ? 'is-invalid' : '';?>" data-ddg-inputtype="unknown" data-twofas-input-listener="true" placeholder="https://www.example.com">
                    <div class="col-2">
                        <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
                    </div>
                </div>
                
                <?php if (isset($errors['name'])): ?>
                    <?php foreach ($errors['name'] as $error): ?>
                        <div class="alert alert-danger small">
                            <?= htmlspecialchars($error) ?>
                        </div>
                    <?php endforeach ?>
                <?php endif ?>
            </form>
        </div>
    </div>
</main>

<?php require 'components/footer.phtml'; ?>
