<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'Анализатор страниц' ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="/favicon.ico">
</head>
<body class="d-flex flex-column min-vh-100">
    <header class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= htmlspecialchars($router->urlFor('home')) ?>">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link <?= ($itemMenu ?? '') === 'main' ? 'active' : '' ?>" href="<?= htmlspecialchars($router->urlFor('home')) ?>">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link <?= ($itemMenu ?? '') === 'urls' ? 'active' : '' ?>" href="<?= htmlspecialchars($router->urlFor('urls.index')) ?>">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <?php require 'components/messages.phtml'; ?>
    
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <?= $content ?>
        </div>
    </main>
    
    <footer class="flex-shrink-0 border-top py-3 mt-5">
    <div class="container-lg">
        <div class="text-center">
            <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
        </div>
    </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>