<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'Анализатор страниц' ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="/favicon.ico">
</head>
<body class="d-flex flex-column min-vh-100">
    <?php require 'components/header.phtml'; ?>
    <?php require 'components/messages.phtml'; ?>
    
    <?php if (isset($content)): ?>
        <?= $content ?>
    <?php else: ?>
        <main class="flex-grow-1">
            <div class="container-lg mt-3">
                <?php require $template ?>
            </div>
        </main>
    <?php endif; ?>
    
    <?php require 'components/footer.phtml'; ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>